apiVersion: v1
kind: ConfigMap
metadata:
  name: mas-cfg
data:
  application.yml: |
    app:
      version: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service
  labels:
    app: mas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mas
  template:
    metadata:
      labels:
        app: mas
    spec:
      containers:
        - name: master-service
          image: ghcr.io/tomkre/eds-master-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: '1.6'
          volumeMounts:
            - mountPath: /workspace/config
              name: mas-cfg-vol
      volumes:
        - name: mas-cfg-vol
          configMap:
            name: mas-cfg