apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service
spec:
  template:
    spec:
      containers:
        - name: master-service
          env:
            - name: APP_VERSION
              value: '2'