apiVersion: v1
kind: Pod
metadata:
  name: master-service
  labels:
    app: mas
spec:
  containers:
    - name: master-service
      image: ghcr.io/tomkre/eds-master-service:1.0
      ports:
        - containerPort: 8080
      env:
        - name: APP_VERSION
          value: '1.2'