services:
  dtb:
    image: postgres:17.1-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: pgs
      POSTGRES_PASSWORD: pwd
  sbs-app:
    depends_on:
      - dtb
    image: tomkre/eds-app:1.0
    container_name: eds_app
    ports:
      - 8082:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dtb:5432/master
      SPRING_DATASOURCE_USERNAME: pgs
      SPRING_DATASOURCE_PASSWORD: pwd
