name: Commit Stage
on: push
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Build, unit and integration tests
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Generated test report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/*.xml'
#      - name: Code vulnerability scanning
#        uses: anchore/scan-action@v6
#        id: scan
#        with:
#          path: "${{ github.workspace }}"
#          fail-build: false
#          severity-cutoff: high
#      - name: Upload sarif file
#        uses: actions/upload-artifact@v4
#        with:
#          name: sarif-report
#          path: ${{ steps.scan.outputs.sarif }}
#      - name: Upload vulnerability report
#        uses: github/codeql-action/upload-sarif@v3
#        if: success() || failure()
#        with:
#          sarif_file: ${{ steps.scan.outputs.sarif }}